<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="8950" started-at="2020-08-14T19:48:32 PDT" finished-at="2020-08-14T19:48:41 PDT">
    <groups>
    </groups>
    <test name="Default test" duration-ms="8950" started-at="2020-08-14T19:48:32 PDT" finished-at="2020-08-14T19:48:41 PDT">
      <class name="mavensample.script.Testscript">
        <test-method status="PASS" signature="setup()[pri:0, instance:mavensample.script.Testscript@76707e36]" name="setup" is-config="true" duration-ms="8428" started-at="2020-08-14T19:48:32 PDT" finished-at="2020-08-14T19:48:40 PDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="verifyusername()[pri:1, instance:mavensample.script.Testscript@76707e36]" name="verifyusername" duration-ms="142" started-at="2020-08-14T19:48:40 PDT" finished-at="2020-08-14T19:48:40 PDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyusername -->
        <test-method status="FAIL" signature="validatepassword()[pri:2, instance:mavensample.script.Testscript@76707e36]" name="validatepassword" duration-ms="316" started-at="2020-08-14T19:48:40 PDT" finished-at="2020-08-14T19:48:41 PDT">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[Unexpected result for screenshot command: null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: Unexpected result for screenshot command: null
at org.openqa.selenium.remote.RemoteWebDriver.getScreenshotAs(RemoteWebDriver.java:304)
at utils.Utils.screenshot(Utils.java:18)
at mavensample.script.Testscript.validatepassword(Testscript.java:37)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validatepassword -->
      </class> <!-- mavensample.script.Testscript -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
